name: Test Run

on:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@main
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Set up FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert Video
      run: |
        # Download Files from URL.txt
        cd videos

        # Read URLs from url.txt and download each file
        while IFS= read -r url; do
            USER_AGENT="Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.3"
            curl -L -A "$USER_AGENT" --parallel -O -J "$url"

        # Check if the file exists before proceeding
            echo "$(ls)"
            rm -rf "url.txt"
            mv *.* 
            VIDEO_FILE="$(ls)"
            if [ -f "$VIDEO_FILE" ]; then
                ffmpeg -n -loglevel error -i "$VIDEO_FILE" -vcodec libx264 -crf 28 -preset faster -tune film "1.$VIDEO_FILE"
                rm -rf "$VIDEO_FILE"
            else
                echo "Error: File $VIDEO_FILE not found."
            fi
        done < url.txt

    - name: Upload ReVanced Applications
      if: inputs.UPLOAD
      uses: termux/upload-release-action@master
      with:
        repo_name: ${{ github.repository }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: "${{ github.run_id }}"
        tag: "${{ github.run_id }}"
        checksums: sha256
        file: videos/*
        overwrite: true
        file_glob: true
        prerelease: false
