name: Test Run

on:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@main
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Download Prerequisites
      run: |
        MAIN_URL=""
        mkdir videos
        cd videos
        wget "$MAIN_URL"
        VIDEO_FILE=$(ls)
        ffmpeg -n -loglevel error -i "$VIDEO_FILE" -vcodec libx264 -crf 28 -preset faster -tune film "1.$VIDEO_FILE"

    - name: Upload ReVanced Applications
      if: inputs.UPLOAD
      uses: termux/upload-release-action@master
      with:
        repo_name: ${{ github.repository }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: "${{ github.run_id }}"
        tag: "${{ env.MAIN_TAG }}"
        checksums: sha256
        file: revanced/release/*
        overwrite: true
        file_glob: true
        prerelease: false
