name: Test Run

on:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@main
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Convert Video
      run: |
        MAIN_URL="https://t.ly/lFbQx"
        mkdir -p videos
        cd videos
        wget "$MAIN_URL"

        # Capture the filename from the URL
        VIDEO_FILE=$(basename "$MAIN_URL")

        # Check if the file exists before proceeding
        if [ -f "$VIDEO_FILE" ]; then
          ffmpeg -n -loglevel error -i "$VIDEO_FILE" -vcodec libx264 -crf 28 -preset faster -tune film "1.$VIDEO_FILE"
          rm -rf "$VIDEO_FILE"
        else
          echo "Error: File $VIDEO_FILE not found."
        fi

    - name: Upload ReVanced Applications
      if: inputs.UPLOAD
      uses: termux/upload-release-action@master
      with:
        repo_name: ${{ github.repository }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: "${{ github.run_id }}"
        tag: "${{ github.run_id }}"
        checksums: sha256
        file: videos/*
        overwrite: true
        file_glob: true
        prerelease: false
