name: Test Run

on:
  workflow_dispatch:
    inputs:
      BUILD:
        description: "Build Packages"
        type: boolean
        default: true

      SIGN:
        description: "Sign Packages"
        type: boolean
        default: true

      ARCHIVE-PACKAGES:
        description: "Archive Packages"
        type: boolean
        default: false

      UPLOAD:
        description: "Upload Packages"
        type: boolean
        default: true

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@main
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Download Prerequisites
      run: |
        cd revanced/assets/temp
        chmod +x download.prerequisites.sh
        ./download.prerequisites.sh

    - name: Upload ReVanced Applications
      if: inputs.UPLOAD
      uses: termux/upload-release-action@master
      with:
        repo_name: ${{ github.repository }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: "${{ github.run_id }}"
        tag: "${{ env.MAIN_TAG }}"
        checksums: sha256
        file: revanced/release/*
        overwrite: true
        file_glob: true
        prerelease: false
